bitwalker/distillery

lib/mix/lib/releases/archiver.ex
Closes #12 
Unfortunately, I didn't know how to add a proper test for this. I tested this with my app locally and it seemed to work correctly.
=> Fix archiver crashing on erts path

lib/mix/lib/releases/archiver.ex
=> Include Consolidated BEAM Files

docs/Common Issues.md
=> Fix a few typos

lib/mix/lib/releases/plugins/plugin.ex
I've clarified the docs of the Plugin module, since they were out of sync with reality.
If you want me to make any changes/have any comments, just let me know!
=> Improve documentation of plugins

docs/Phoenix Walkthrough.md
=> Missing a `do` in mix command

docs/Phoenix Walkthrough.md
application name should be `phoenix_distillery` not `phoenix-distillery`
=> you can't use '-' in an application name

README.md
I think that this was just an omission from the last update.
=> update to latest release in readme instructions.

docs/Plugins.md, lib/mix/lib/releases/config/config.ex, lib/mix/lib/releases/plugins/plugin.ex, test/config_test.exs, test/fixtures/standard_app/rel/config.exs, test/fixtures/standard_app/rel/release_plugin.ex, test/fixtures/standard_app/rel/sample_app_plugin.ex
=> Allow passing options to plugins

lib/mix/lib/releases/assembler.ex, lib/mix/lib/releases/config/config.ex, lib/mix/lib/releases/models/profile.ex, priv/templates/boot.eex
I added pre_upgrade/post_upgrade hooks configuration and overlays, but I'm not sure if this is a right place to execute them. @bitwalker is it correct?
=> Add pre_upgrade/post_upgrade hooks

priv/templates/boot.eex, priv/templates/release_utils.eex
Issues spotted while debugging my use of `command` and `console_clean`.
=> Code paths fixes

docs/Phoenix Walkthrough.md
changed the phoenix walkthrough file to use the correct brunch flag for production
=> brunch production flag

lib/distillery/tasks/init.ex
=> Fix Elixir 1.4 warnings

priv/templates/boot.eex
=> Fixed typo in boot.eex comments

docs/Phoenix Walkthrough.md
Phoenix website is not reachable using https use http instead.
=> Phoenix website is not reachable using https so use http.

lib/mix/lib/releases/plugins/plugin.ex
depends on https://github.com/bitwalker/distillery/pull/179
adds defoverrideable and default implementations for plugins
=> implement default behaviours for plugin callbacks

docs/Phoenix Walkthrough.md
I have corrected the path given in the doc for "logo" class, given path was  _file: web/static/css/app.css_ but it should be _file: web/static/css/phoenix.css_.
=> Corrected the path for '.logo' class

docs/Running Migrations.md
Unused var, should be passed to `:code.priv_dir`.
=> Update Running Migrations.md

.travis.yml
Extend the scope of which versions of Elixir and OTP are tested against. Thanks!
=> Extend Travid build matrix

priv/templates/boot_win.eex
#280
This PR provides the solution I described in Issue #280.
=> BugFix: Run Release with option foreground on Windows does not work.

docs/Phoenix Walkthrough.md, docs/Use With Phoenix.md
[Discussion here](https://elixirforum.com/t/distillery-version-nil-in-sys-config-in-phoenix-umbrella-app/6592).
=> In docs, set Phoenix app version with Application instead of Mix in case app is in umbrella

README.md
=> Fix broken Elixir Forum Link

docs/Running Migrations.md
Great documentation, thanks!
I generalized the Ecto DB migration page so that the code can leverage existing configurations.  In particular, the `:ecto_repos` defined in
```
config :myapp, ecto_repos: [MyApp.Repo]
```
And extracting the application from the `__MODULE__`
The new code is a little more abstract, which might make it a bit harder for users to understand, but I think it makes good use of existing information to avoid duplication.
I only tested the "migrate" code (as I am currently NOT integrating seeds into my release process), I am not sure if you had a nice sandbox to easily test, or if you want to push back onto me to test.
Here's the output from my `migrate`  based on the code I updated.
```
iex(1)> Nameui.ReleaseTasks.migrate
Running migrations for namedb
[info] Already up …
```
=> Remove need to explicitly map :myapp and MyApp.Repo in Migrations documentation

docs/Running Migrations.md
Fix the migrations example code, so it's functional.
=> Fix running migrations doc.

docs/Running Migrations.md
The "repo" name was fixed in sample code. I just put it dynamically using `Mix.Ecto` module.
=> Allow migrations by Repo

docs/Running Migrations.md
Detail here https://github.com/bitwalker/distillery/issues/361, I've tested it on macOS & Ubuntu 16.04.
=> fix broken example

priv/templates/boot_win.eex
These commits fix issues in the batch template for Windows.
This is the unsquashed (and slightly revised) version of #376.
=> Fixes Windows batch script

README.md
I think it will _slightly_ improve the user/dev experience, when reading the readme to have a link to the license file.
=> Add link to LICENSE.md

docs/Use With systemd.md, mix.lock
* Change the format of systemd docs to render correctly. Right now they look very bad:
* Also update ex_doc.
=> Reformat systemd docs to render dorrectly 

docs/Getting Started.md
Some minor grammatical and readability tweaks.
=> Tweak "Getting Started.md"

lib/mix/lib/releases/assembler.ex, priv/templates/boot_win.eex
Updated changes from https://github.com/bitwalker/distillery/pull/291
=> Fix command on Windows

docs/Phoenix Walkthrough.md
Fixes a couple of doc typos.
- [x ] Commits were squashed into a single coherent commit
=> Fix typos in phoenix walkthrough

docs/guides/running_migrations.md
Although somewhat intuitive, it was unclear to me where the migration script configuration should go. This PR makes that location explicit.
FYI: the docs on the documentation site do not align with the repo, the repo ReleaseTasks example code works, but the sample code from the doc site does not.
=> Be more specific about where to include config for migration script

docs/guides/phoenix_walkthrough.md, docs/introduction/release_configuration.md, docs/introduction/terminology.md, docs/introduction/up_and_running.md, docs/introduction/walkthrough.md
As promised in Slack, I gonna go through the whole documentation. Found some typos on my way and thought it would be good to create a WiP PR where I fix those as I move along. 
Gonna squash them in the end.
=> WiP: Documentation fixes

docs/guides/phoenix_walkthrough.md
There are some broken links in Phoenix walkthrough docs section. This PR will fix it.
=> Fix broken links in phoenix walkthrough

lib/mix/lib/releases/assembler.ex
I am open to structuring this differently :)
=> Only copy apps from erts path if the app is part of erts

lib/distillery/tasks/release.ex
=> Silence success message for quiet and slient verbosity types

CHANGELOG.md, mix.exs
=> Changelog improvements

docs/extensibility/boot_hooks.md, docs/extensibility/custom_commands.md
=> Fix broken link in docs

lib/mix/lib/releases/plugins/plugin.ex
implentations -> implementations
=> fix a typo

docs/guides/deploying_to_aws.md
=> Fix typo in deploying_to_aws.md

docs/config/distillery.md
=> Runtime config link was broken

docs/extensibility/boot_hooks.md
`pre_start_hook` -> `pre_start_hooks`, `post_start_hook` -> `post_start_hooks`
=> use new hooks declaration in example

mix.exs
This is needed so projects which depend on distillery could use the `:locals_without_parens` setting exported from `.formatter.exs`.
=> Package .formatter.exs

docs/guides/systemd.md
Two very minor fixes to the systemd guide
=> Systemd guide

lib/mix/lib/releases/checks.ex
This is not the intention of `else` so change to `case` instead. Also fixes compilation on Elixir master.
=> Change else clause to case

docs/guides/running_migrations.md
Ecto 3 splits out migrations into a new application (`ecto_sql`) which will need to be started to run migrations.
=> Update for latest Ecto

lib/mix/lib/releases/models/release.ex
There is a case when you want to add an application to release which don't exist.  For example umbrella app or an app from debian package.
Right now you'll get a nasty error:
```
nil.name()
(distillery) lib/mix/lib/releases/models/release.ex:532: Mix.Releases.Release.do_add_app/4
(distillery) lib/mix/lib/releases/models/release.ex:547: Mix.Releases.Release.do_add_children/4
(distillery) lib/mix/lib/releases/models/release.ex:507: Mix.Releases.Release.add_apps/3
(distillery) lib/mix/lib/releases/models/release.ex:476: Mix.Releases.Release.apps/1
(distillery) lib/mix/lib/releases/models/release.ex:330: Mix.Releases.Release.apply_configuration/3
(distillery) lib/mix/lib/releases/assembler.ex:28: Mix.Releases.Assembler.pre_assemble/1
(distillery) lib/mix/lib/releases/assembler.ex:46: …
```
=> Validate every app before adding to graph

docs/guides/deploying_to_google_cloud_platform.md
This PR adds a simple guide of deploying a release to a VM on Google Cloud Platform.
=> Add guide for releasing to Google Cloud Platform

docs/introduction/terminology.md
=> Fix typo in terminology.md

docs/guides/phoenix_walkthrough.md
| before | after |
| - | - |
| <img width="1237" alt="2019-01-05 18 19 06" src="https://user-images.githubusercontent.com/10890/50722905-9d27da00-1119-11e9-9480-da0da71c7f32.png"> | <img width="1212" alt="2019-01-05 18 19 42" src="https://user-images.githubusercontent.com/10890/50722907-a2852480-1119-11e9-83cf-0fa68ca19e65.png"> |
considered, it must …
=> Fix listing in the document of Guides/Phoenix

docs/guides/working_with_docker.md
Updated `cd` command because now if `PHOENIX_SUBDIR` need to be changed to something like `apps/web_api` it will fail on this step.
=> Update mix phx.digest part

docs/guides/running_migrations.md
=> Default to pool_size 2 for ecto 3

docs/extensibility/config_providers.md
Especially nasty is the infinite loop.
=> Fix JsonConfigProvider example

docs/guides/phoenix_walkthrough.md
Updated the Phoenix walkthrough to work with 1.4.10
=> Phoenix walkthrough doc update

docs/upgrading_to_2_0.md
This updates a code block in migration guide to look nicer.
=> Update markup in migration guide slightly
