bitwalker/distillery

lib/mix/lib/releases/config/config.ex

Correct the case-clause which validates the overlay tuple. The method
was designed for tuples with the format `{:copy, ["src", "target"]}`
but `Mix.Releases.Overlays` only accepts tuples which don't carry the
options in a list. This resulted in a ArgumentError, which caused an
`Mix.Releases.Config.LoadError`, which threw an error message
in lib/distillery/tasks/release.ex at line 73.
Now the case clause matches overlay tuples with one or two arguments
and therefore follows the spec in `Mix.Releases.Overlays`.

Fix validation of overlays

---

docs/Boot Hooks.md

The keys are pre_start_hook and post_start_hook in Mix.Releases.Profile.

Fix boot hooks config in docs

---

priv/templates/boot.eex

this was done in exrm in https://github.com/bitwalker/exrm/pull/109. i just stumbled over this when having multiple apps under different users on the same server. 
only the first app will be able to write to `/tmp/erl_pipes` and all others fail.

keep erl_pipes in release dir

---

lib/distillery/tasks/init.ex

Ran across a bug where stray hidden files inside the `apps` directory cause `mix release.init` to fail...
```
** (File.Error) could not set current working directory to "apps/.DS_Store": not a directory
(elixir) lib/file.ex:1127: File.cd!/1
(elixir) lib/file.ex:1143: File.cd!/2
(elixir) lib/enum.ex:1184: Enum."-map/2-lists^map/1-0-"/2
lib/distillery/tasks/init.ex:80: Mix.Tasks.Release.Init.get_umbrella_bindings/1
lib/distillery/tasks/init.ex:46: Mix.Tasks.Release.Init.run/1
(mix) lib/mix/task.ex:296: Mix.Task.run_task/3
(mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
```
I fixed this by using `Path.wildcard` which excludes hidden files by default. This also means we don't need to `Path.join` the `apps_path` back in when generating the `apps` list.
I ran this locally, and it fixed the problem, …

Exclude hidden files from umbrella apps list

---

lib/mix/lib/releases/assembler.ex
lib/mix/lib/releases/models/profile.ex
test/config_test.exs
test/fixtures/standard_app/rel/config.exs
test/fixtures/standard_app/rel/release_plugin.ex
test/fixtures/standard_app/rel/sample_app_plugin.ex
test/integration_test.exs

When specifying a plugin in an environment only (and not a release) the
plugin is prepended to the profile.plugins attribute. However since
this defaults to nil, the result is an improper list in the format:
[SampleApp.TestPlugin | nil]
This commit fixes it so that the profile.plugins defaults to an empty
list, resulting in:
[SampleApp.TestPlugin | []]
A test has been added which loads a sample plugin from the rel
directory and verifies that the list contains a list with the plugin.
This test will fail when the list is an improper list.

Fix plugins only specified in an environment

---

docs/Walkthrough.md

Current release is 0.9.2 but the guide still instructs ~> 0.8.

Bump up distillery dependency version to ~> 0.9.

---

lib/mix/lib/releases/assembler.ex

There might be cases when the consolidated directory is not present. In that case the build would fail. So I added a check if it exists.
fixes #47

don't fail if consolidated directory does not exist

---

priv/templates/boot.eex

As mentioned, this fixes path resolution for erl on systems without any erlang installed

fix path resoltuion for erl when using include_erts

---

docs/Phoenix Walkthrough.md
docs/Use With Phoenix.md
docs/Walkthrough.md
mix.exs

As discussed in #2, This PR adds two documentation pages to the project. First is a walkthrough building a simple Phoenix application (without ecto) to take readers through initializing an application, creating a base release, and hot upgrading 3 times. I opted to not include Ecto at this time for no other reason than the sample project I created to test distillery did not use Ecto. I am happy to extend this guide with Ecto specific documentation as needed.
The second Page is a semi duplicative document which adds some Phoenix specific information to the general Walkthrough page. I feel like this page is useful, but probably should refer to the Walkthrough page for some information and limit itself to "Phoenix only" information. Im all ears on this one.
NOTE: In #2 @bitwalker you …

Phoenix Walkthrough and "Use with Phoenix" Draft

---

priv/templates/boot_loader.eex

I'm not quite sure where to put a test for this, or if it's even worth a test
When the generated shell script mentioned at the end of `mix release` is
run with CDPATH set on a system where `/bin/sh` is really a `bash` then
`cd` can echo the directory it's changing to. This makes the setting of
`SCRIPT_DIR` fail:
```
==> Release successfully built!
You can run it in one of the following ways:
Interactive: rel/la_famiglia/bin/la_famiglia console
Foreground: rel/la_famiglia/bin/la_famiglia foreground
Daemon: rel/la_famiglia/bin/la_famiglia start
$ rel/la_famiglia/bin/la_famiglia console
rel/la_famiglia/bin/la_famiglia: line 5: cd: /Users/mike/Projects/influitive/la-famiglia/rel/la_famiglia/bin …
```

make bash script unset CDPATH to avoid no such file or directory errors

---

lib/distillery/tasks/release.ex

Trivial change to ensure `:distillery` is visible in the list of loaded_applications. Needed for a `conform` PR to come soon.
There may be a better place to put this. Alternatively, we may need it in more/all Mix entry points.

tasks/release: ensure :distillery is loaded

---

lib/distillery/tasks/init.ex
lib/mix/lib/releases/assembler.ex
lib/mix/lib/releases/models/profile.ex
lib/mix/lib/releases/utils.ex
priv/templates/example_config.eex
priv/templates/vm.args.eex
test/fixtures/standard_app/rel/config.exs

Previously, the erlang cookie generated in vm.args was easily guessable, putting installations and developers at risk.
I propose making an appropriate config option mandatory in case the user does not provide a vm.args file.

Generate vm.args with configurable cookie

---

priv/templates/boot.eex

More reliable mechanism to resolve the installation directory. Updated to strict shell, tested against dash.
~
Canonicalizes directory, resolving any symlink,
uses (g)readlink -f where available, or falls back
on hand-rolled function.

boot: Improve release directory resolution

---

priv/templates/boot.eex

Builds on #79 (the patch to review here is 5e3ec09 ) , requires https://github.com/bitwalker/conform/pull/87 .
Brings back R_M_D as `running-enviroment`, to place logs, pipes and generated config files.
* Simplifies symlink-to-dev-files support
* Files in `running-environment` get a comment indicating "Generated, create/edit in path/to/release/foo"
* Does not ovewrite release or user-edited files.
* Supports read-only releases (immutable from the PoV of the process).

boot: re-establish RELEASE_MUTABLE_DIRECTORY, with cleaner semantics

---

priv/templates/boot.eex

... or confused users setting them to the same location where
we expect to write the transient copy.

boot: guard VMARGS_PATH and SYSCONFIG_PATH from recursive calls

---

priv/templates/boot.eex

When running a release on a system that didn't have the `erl` script in the PATH I got no output (even help). This PR adds a note saying erlang wasn't found and points the user to the area they should look in.  
Continuation of #71.

Make sure $__erl is not blank

---

lib/mix/lib/releases/utils.ex

The extra brace made the search for libraries fail.

FIX: extra brace in string

---

docs/Phoenix Walkthrough.md

Link was not working because surrounded by backquotes.

Fix link to upgrades-and-downgrades

---

priv/templates/boot.eex

I fixed work of REPLACE_OS_VARS #96 . 
Since moving of original file is not needed anymore with new mutable directory, I make a awk replacement using temp file.

Fix REPLACE_OS_VARS

---

priv/templates/boot.eex

This is a change to the boot shell script to address https://github.com/bitwalker/distillery/issues/100
A bit quick and dirty as I didn't have a ton of time to work on this, but the test suite is passing and manual test confirms this has the desired effect of allowing the cookie file to be created in a pre-start hook.
Cheers!
- Mike

Defer cookie validation until after pre-start hook(s)

---

priv/templates/boot.eex

This pr is fixing bug with execution of hooks inside of busybox shell, bug described in #113

Make execution of hooks to work on busybox

---

lib/mix/lib/releases/logger.ex
test/logger_test.exs

After `mix.release` command, terminal output color doesn't pop to original.
```
==> Release successfully built!
You can run it in one of the following ways:
Interactive: rel/my_app/bin/my_app console
Foreground: rel/my_app/bin/my_app foreground
Daemon: rel/my_app/bin/my_app start
my_user$
```
minimal code:
```elixir
IO.puts IO.ANSI.format([IO.ANSI.bright <> IO.ANSI.green, "hello", IO.ANSI.reset])
IO.puts "world"
```
My terminal regular color is white. The command should back to white (original) color.
The commit is fix changed output color.

fix changed output color

---

lib/distillery/tasks/init.ex

--name option was documented but not implemented for release.init task.
Could not find tests for mix tasks suppose only the internal logic is being tested.
Tested it with a local deployment of mine and seemed to work.

Accept --name option as documented for release.init

---

lib/mix/lib/releases/assembler.ex

Found what pre stop hook overlay copy had  a typo, fixed.

Fix typo in pre_stop hook overlay

---

lib/distillery/tasks/init.ex

Fixes a couple of uses of the word `it's` that were possessive and consequently should have omitted the apostrophe.

[TYPO] it's -> its

---

docs/Umbrella Projects.md

If I understand the documentation correctly this little documentation change helps keeps things consistent vs having a random inconsistency in the name of the release in the code example for docs/Umbrella Projects.md.

Makes the code example consistent with explanation

---

lib/distillery/tasks/init.ex
lib/mix/lib/releases/utils.ex

Nerves requires some additional work to be done in the release config. Instead of recreating the generator, we would like to call `release.init` upstream and pass through a path to our custom template.

allow passing a custom eex template to use to the init generator

---

lib/mix/lib/releases/archiver.ex

Archiver would fail when include_system_libs is set to a path instead of a boolean.

fix archiver when passing path in include_system_libs

---

lib/distillery/tasks/init.ex

fix nil to atom issue for release.init in umbrella projects when :name is nil

fix nil to atom issue for release.init in umbrella projects when :name is nil

---

lib/distillery/tasks/init.ex
priv/templates/example_config.eex
test/fixtures/standard_app/rel/config.exs

Closes #149
`mix release.init` will create an example release config with distinct cookies for dev and prod to help avoid accidental node connections between environments.
I debated how to provide the cookies to the config template. I didn't want to remove the existing `:cookie` binding so as to not break any existing custom config templates. Now I see that the custom template feature is brand new, so perhaps that's not a concern.  
I ended up providing an additional binding for the `get_cookie` function so the template could provide cookies for an arbitrary number of environments.  
Let me know if you'd prefer to handle this differently.
I didn't see any existing test coverage for the `release.init` task. I started working on some general `release.init` tests, not specific to this …

Update release.init example config to have distinct cookies

---

lib/mix/lib/releases/appups.ex
test/appup_test.exs

Fixes invalid `:update` tuple for supervisors. See issue #141 
(Sorry, since I squashed/force-pushed, GitHub didn't let me reopen #150)

appups: fix :update for supervisor

---

test/fixtures/init_test_app/.gitignore
test/fixtures/init_test_app/config/config.exs
test/fixtures/init_test_app/init_test_config.eex
test/fixtures/init_test_app/lib/init_test_app.ex
test/fixtures/init_test_app/mix.exs
test/init_test.exs
test/integration_test.exs
test/mix_test_helper.exs

Adding some basic test coverage for the `release.init` mix task.
It merely verifies the existence of `rel/config.exs` generated from the example, and uses a custom template to verify that certain bindings are available within the template.
- ~~New functions have typespecs, changed functions were updated~~
- ~~Same for documentation, including moduledocs~~

Add tests for release.init mix task

---

lib/mix/lib/releases/config/config.ex

Don't force arguments passed to current_version to be an atom.

Allow variable to be used for current_version with environment/release macros in config

---

priv/templates/boot.eex

Use case: read the (conform-driven) configuration, to set DB connection, etc for the 'prepare/seed' actions that are the main use case for the `command` facility.

boot: run pre_start hooks when running commands

---

priv/templates/boot.eex

Use case: we have init script for service/app 'x' which depends on service/app 'y' being up. This can be run single-node or multi-node, so there may be many `y@host` erlang nodes that could be responsive.
Using pingpeer (and a for loop, or the `parallel` utility) we can check whether _any_ of the hosts is serving `y` before starting `x`.

boot: bring back pingpeer

---

priv/templates/boot.eex

allows Elixir code to distinguish between 'command' and 'start' cases.
------
@bitwalker - for discussion, would you consider an envvar like this?
Some apps need to know they are initializing in the context of a `command`  invocation to avoid fully starting some of their deps (ie: connecting to other nodes, etc).
An envvar indicating the boot command can help the application code decide...

boot: export DISTILLERY_TASK for Elixir runtime

---

docs/Phoenix Walkthrough.md

-P now signifies port which does not make sense in the context of the
build (b) command
Change concerns the Phoenix Walkthrough documentation
Fixes #174

Fix documentation: Brunch 2.0 switched -p and -P

---

lib/mix/lib/releases/plugins/plugin.ex

Plugin callbacks are being called with arity 1 with the exception of after_cleanup. This fixes the plugin behaviour callbacks and docs

fix plugin behaviour and docs

---

lib/mix/lib/releases/assembler.ex
lib/mix/lib/releases/models/release.ex

moved get_code_paths/1 to Release and made it public. I need to generate some custom .boot files which require that I can get this list.

get_code_paths/1 to Release and make it public

---

docs/Upgrades and Downgrades.md

A small documentation change to prevent confusion. If @jeg2 and I are reading it right, it seems like the example version number didn't match the ones from the sentence.

Fix typo in example version number

---

lib/mix/lib/releases/models/app.ex

In Elixir 1.4, we can explicitly state that a dependency is not to be included in `applications` via `runtime: false` option. This PR takes into account this option and ignores such dependencies. Consequently, missing application warnings are not reported for these deps.

ignore deps not used in runtime

---

priv/templates/boot.eex

Multiple people getting crash dumps when trying to start applications using distillery and edeliver (https://elixirforum.com/t/edeliver-wont-start-project-at-production/2818).  Traced issue to the way the sys.config file is being created in two steps, leaving a race condition that allows an invalid sys.config file for a small period of time.  Create the output more atomically for a solution.

Reduce the chance of invalid sys.config buring boot

---

docs/Use With systemd.md

It is not 'System D', it's 'systemd', per https://www.freedesktop.org/wiki/Software/systemd/#spelling
N/A
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bitwalker/distillery/194)

Fix systemd naming typo

---

lib/distillery/tasks/release.ex

Was perusing the changes in the codebase for the executables feature and noticed this. Looks like win32 would exit on every run, rather than when run with the `--executable` flag, as was the intention

Fix win32 executable exit conditions

---

docs/Running Migrations.md

We don't need to start the full pool - one connection is enough for running migrations. This can be important in environments with limited connections to database - running migrations would "steal" connection from real application.
Also, the regular call syntax is clearer than `apply/3`, especially when passing options.

Update Running Migrations.md

---

priv/templates/example_config.eex

Properly closes #12 - the issue was closed by accident.
>Runtime tools are important if anyone wants to use most of the awesome tooling erlang gives us for debugging running systems. With the applications configuration in releases I feel like we have a perfect place to define this - it doesn't really make sense for the application itself to depend on the runtime_tools. I think it would be reasonable to include the application by default.
>
>It's relatively large with 296K, but I don't think it matters that much for most people, and for those who do care, it's easy to remove.

Generate the default config including runtime_tools

---

docs/Configuration.md
docs/Overlays.md
docs/Runtime Configuration.md
lib/distillery/tasks/release.ex
lib/mix/lib/releases/assembler.ex
lib/mix/lib/releases/config/config.ex
lib/mix/lib/releases/models/profile.ex
lib/mix/lib/releases/models/release.ex
priv/templates/boot.eex
test/fixtures/standard_app/rel/config.exs

This patch adds the `run_erl_env` configuration parameter, which
allows the user to apply environment variables to the `run_erl` process
that is responsible for starting and running a release.
Set it like this:
set run_erl_env: "RUN_ERL_LOG_MAXSIZE=10000000 RUN_ERL_LOG_GENERATIONS=10"
This parameter can be overridden by setting the `RUN_ERL_ENV` parameter
at the command line when running `mix release`.

Added run_erl_env parameter to provide runtime configuration of run_erl

---

docs/Getting Started.md

Fixes syntax typos in the configuration example of "Getting Started".

Fix typos in `Getting Started.md`

---

docs/Configuration.md

Apologies for the drive-by PR, but I was banging my head against my keyboard for about an hour trying to emulate the cookie-generation in this example config before I realized I just needed to encode the return value of `:crypto.hash\2` to make it work. Also, I piped the result to `String.to_atom\1` to extend the pipeline, instead of relying on string interpolation.
_(None of the following apply.)_

Fixed cookie-generation line in example config

---

lib/mix/lib/releases/config/config.ex
test/config_test.exs
test/fixtures/standard_app/rel/another_release_plugin.ex
test/fixtures/standard_app/rel/config.exs

Ensure plugins are executed in the order they are defined in config
Previously plugins were accumulated using `[new | plugins]` - this would
result in the following case:
plugin MyPlugin1  # Executed second
plugin MyPlugin2  # Executed first
It makes more sense to run these in the following order:
plugin MyPlugin1  # Executed first
plugin MyPlugin2  # Executed second
This is achieved using `plugins ++ [new]`
This could possibly be a breaking change for anyone relying on reverse
ordering.

Ensure plugins are executed in the order they are defined in config

---

docs/Use With systemd.md

Tested with release. Setting Type=forking causes app to restart correctly on failure.
Per the docs:
If set to forking, it is expected that the process configured with ExecStart= will call fork() as part of its start-up. The parent process is expected to exit when start-up is complete and all communication channels are set up. The child continues to run as the main daemon process. This is the behavior of traditional UNIX daemons. If this setting is used, it is recommended to also use the PIDFile= option, so that systemd can identify the main process of the daemon. systemd will proceed with starting follow-up units as soon as the parent process exits.

change systemd.md remove RemainAfterExit=yes replace with Type=forking

---

priv/templates/boot.eex

This can be necessary for generation of configuration via conform, for
example for configuration of a database and running migration via
/bin/myapp command MyApp run_migration

run pre_configure hook before command execution

---

README.md

Bumped the version in the `mix.exs` example to `1.4` and added a link to the signup page for the Slack channel

Bump version in README + add link to Slack channel

---

priv/templates/boot.eex

Using edeliver and the instructions here: https://github.com/boldpoker/edeliver/wiki/Use-per-host-configuration - sys.config and vm.args become symlinks in the release directory.
I was having trouble getting upgrades to work using this setup and I narrowed it down to where it tries to back up the files and copy the existing ones over.
Using the archive (-a) and force (-f) flags I managed to get upgrades to work using symlinked sys.config and vm.args files.
I also added a verbose (-v) flag just to give a bit more information about what is being copied, where.

sys.config and vm.args not being copied correctly during upgrade if they are symlinks

---

priv/templates/executable.eex

According to https://github.com/bitwalker/distillery/issues/277, current executable releases cannot be run correctly on OpenBSD, and possibly some other systems. This is because `tar` command does not always read standard output as default. In fact, I wonder how many `tar` commands does.
On OpenBSD, `tar` reads the archives from a tape device `/dev/rst0` instead of standard output: http://man.openbsd.org/tar#f
On FreeBSD, `tar` reads the archives from `/dev/sa0` while on Linux it reads from `/dev/st0`: http://man.openbsd.org/FreeBSD-11.0/tar#f
On Mac OS X, it should behave the same as OpenBSD. However, I guess it would use standard output when it is not blank.
```
-f archive
Filename where the archive is stored.  Defaults to /dev/rst0.  If
set to hyphen (`-') standard output is used.  See …
```

fixed failed extraction on OpenBSD

---

README.md
docs/Phoenix Walkthrough.md
docs/Walkthrough.md

As I understand it, Distillery isn't required at runtime so I added `runtime: false`, as per [the example here](https://elixir-lang.org/blog/2017/01/05/elixir-v1-4-0-released/#application-inference).

Update version to 1.4 and add ‘runtime: false’ in doc deps examples

---

docs/Use With systemd.md

Contains two minor updates to the systemd example for `start` usage
(as opposed to 'foreground')
* The example previously specified both `Type=simple` _and_
`Type=forking`.  Remove the `simple` version.
* The prose calls out the importance of including
`RemainAfterExit=yes`, but this didn't appear in the example
configuration.

Update systemd documentation

---

priv/libexec/commands/command.sh

- Escape the module atom
- Ensure the target module's code is loaded before checking the export
- Ensure CONSOLIDATED_DIR is on the code path
- Fix missing newline escape

Fix the command.sh script

---

lib/mix/lib/releases/assembler.ex

In Elixir 1.5, the consolidation path changed. This affected Distillery since Distillery doesn't use `Mix.Project.consolidation_path/1` but used `Mix.Project.build_path/1` and built the consolidation path manually.
This resulted in not consolidated protocols on Elixir 1.5.
I didn't add tests because I didn't find tests for the old behaviour on a quick look and this is a really bad/urgent bug so I'd rather bring it to attention as soon as possible. I verified the patch works for one of our production application which was affected by the previous behaviour.
I'll go ahead and ping you @bitwalker in case you only have mention notifications on :)
PS `Mix.Project.consolidation_path/1` was available on 1.3 (didn't check when it was introduced, might be there since 1.0) so no backwards compat …

Fix consolidation path

---

docs/Use With systemd.md

Updated examples for use with SystemD. As discussed in https://github.com/bitwalker/distillery/issues/310.
- Remove the recommendation to set `RemainAfterExit=yes`. This doesn't seem to be necessary and prevents SystemD from restarting your app if it crashes.
- We already had examples for
- running app in foreground mode
- running it as a daemon having SystemD attempt to guess the pid
I've added a third example configuration for using SystemD with a pidfile, if you don't want to use foreground and want your app restarted after crashes this is the way to go.
- Add notes about the strengths and weaknesses of the three approaches. I wanted to make it clearer why one would choose a particular configuration over another. The effective differences between the three approaches are
- how logging …

Update systemd docs

---

priv/libexec/commands/attach.sh
priv/libexec/commands/command.sh
priv/libexec/commands/console.sh
priv/libexec/commands/describe.sh
priv/libexec/commands/escript.sh
priv/libexec/commands/eval.sh
priv/libexec/commands/foreground.sh
priv/libexec/commands/help.sh
priv/libexec/commands/install.sh
priv/libexec/commands/pid.sh
priv/libexec/commands/ping.sh
priv/libexec/commands/pingpeer.sh
priv/libexec/commands/reboot.sh
priv/libexec/commands/reload_config.sh
priv/libexec/commands/remote_console.sh
priv/libexec/commands/restart.sh
priv/libexec/commands/rpc.sh
priv/libexec/commands/rpcterms.sh
priv/libexec/commands/start.sh
priv/libexec/commands/stop.sh
priv/libexec/commands/unpack.sh
priv/libexec/config.sh
priv/libexec/env.sh
priv/libexec/erts.sh
priv/libexec/helpers.sh
priv/libexec/logger.sh
priv/templates/boot.eex
priv/templates/boot_loader.eex

Bash is not always installed at `/bin/bash`. This breaks distillery on FreeBSD for example. Use `/usr/bin/env bash` instead.
No need to change the boot_check script as it's already using `which` to check if bash is present.

Bash: Use correct shebangs

---

priv/libexec/commands/attach.sh
priv/libexec/commands/command.sh
priv/libexec/commands/console.sh
priv/libexec/commands/describe.sh
priv/libexec/commands/escript.sh
priv/libexec/commands/eval.sh
priv/libexec/commands/foreground.sh
priv/libexec/commands/help.sh
priv/libexec/commands/install.sh
priv/libexec/commands/pid.sh
priv/libexec/commands/ping.sh
priv/libexec/commands/pingpeer.sh
priv/libexec/commands/reboot.sh
priv/libexec/commands/reload_config.sh
priv/libexec/commands/remote_console.sh
priv/libexec/commands/restart.sh
priv/libexec/commands/rpc.sh
priv/libexec/commands/rpcterms.sh
priv/libexec/commands/start.sh
priv/libexec/commands/stop.sh
priv/libexec/commands/unpack.sh
priv/libexec/config.sh
priv/libexec/env.sh
priv/libexec/erts.sh
priv/libexec/helpers.sh
priv/libexec/logger.sh
priv/templates/boot.eex
priv/templates/boot_check.eex
priv/templates/boot_loader.eex

On FreeBSD, tput is using termcap instead of terminfo -- so the codes are not the same. Also it seems that termcap don't have codes for colors.
This fixes uses ANSII codes when tput fails.

Fallback to ANSII codes if tput fails

---

docs/Custom Commands.md

Fixing the docs to reflect that custom command arguments should start at `$1` not `$2`.  
I was using command line args for a custom command, and I believe the docs might be out of date.  Here is a PR to correct the docs.  If the docs are right and I am wrong, then I would love help understanding what I am presently doing wrong.
I took an existing custom command, and tweaked it to demonstrate what I am observing
```
14:27 /src/namerel (master)$ cat /src/namerel/releases/0.10.0/commands/enable.sh
#!/bin/bash
echo "1 $1"
echo "2 $2"
```
Then when I run it, the args appear to start at `hi` not `enable`
```
14:27 /src/namerel (master)$ ./bin/nameui enable hi
1 hi
2 
```
So I think the docs should start at `$1`

Custom command args start at \$1, not \$2

---

priv/templates/boot_win.eex

Fix **erlsrv** Windows service to respect `RELEASE_MUTABLE_DIR` as [erlsrv `WorkDir`](http://erlang.org/doc/man/erlsrv.html).

Fix to respect `RELEASE_MUTABLE_DIR` as erlsrv WorkDir

---

docs/Use With Phoenix.md

In "Building your release" section of Use with Phoenix the step 3 suggests running `mix release --env=prod` to build a production release. The command will generate a new release inside `_build/dev` which is not production.
The commit fixes the instructions to use `MIX_ENV=prod mix release` instead of `mix release --env=prod`

Fix: release prod command

---

docs/Running Migrations.md

This avoids searching for the correct environment variable and will make the migrate command just work(tm).

add RELEASE_ROOT_DIR to example so the migrate command always works

---

README.md

The link to elixirforum's deployment topic has changed - this PR updates it to the correct link.

correct link to elixirforum deployment topic

---

docs/Phoenix Walkthrough.md

**Why**
Because Phoenix Framework latest version is 1.3 and directory structure changed.
**What**
Update command to use with Phoenix 1.3 to build assets, generate digest and build release.

Update Phoenix Walkthrough for Phoenix 1.3

---

priv/templates/boot_loader_win.eex
priv/templates/boot_win.eex

The current syntax don't work on old Windows as `@call` is not available. That fix improves compatibility with old Windows (tested on Win 7 SP1 32-bit) and results in a cleaner code as `@echo off` is being called once.
Fixes #349.

Use @echo off instead of prefixing all commands with @ on Windows #349

---

docs/Getting Started.md

Documentation was using contraction of "it is" instead of possessive "its."

it's -> its

---

docs/Running Migrations.md

Example was using `seed` rather than `migrate` as indicated by the shell script filename

Fix Running Migrations doc example

---

lib/mix/lib/releases/models/release.ex

It is now possible to retrieve the release environment name (passed in
with `--env=`) using `%Release{env: env}` within plugins.
Closes #354
Allows a plugin to access the release environment name. This is something which should be included for plugins to be able to generate file names/etc based upon the environment name.

Add environment name as atom to %Release struct for use by plugins

---

priv/templates/erl_script.eex
test/integration_test.exs

The generated `erl` script would fail if it was run from a directory containing a space.  The script now uses shell quoting to behave properly in that situation.
Allows the generated `erl` script to run successfully in a path that contains a space.

closes #341

---

CHANGELOG.md
docs/Terminology.md
docs/Walkthrough.md

- it's -> its
- there *is* no significant differences -> there *are* no significant differences
- an upgrades -> an upgrade

fixes typos

---

lib/mix/lib/releases/assembler.ex
test/fixtures/ordered_app/.gitignore
test/fixtures/ordered_app/config/config.exs
test/fixtures/ordered_app/lib/ordered_app.ex
test/fixtures/ordered_app/mix.exs
test/fixtures/ordered_app/rel/config.exs
test/release_test.exs

This change fixes `write_relfile` to generate `.rel` as simple as it possible. `systools` has the ability to make topological sorting for the applications by itself.

Don't change application order by hand, let allow `systools` does it

---

priv/templates/boot_win.eex

I replaced the sleep command with timeout since the sleep command couldn't be found on my Windows 10 Pro (apparently it's only available if you install the Resource Kits). The timeout command is available since Windows Vista.
I also redirected the tasklist output to nul so that it doesn't fill the command prompt.

Boot win fixes

---

priv/templates/example_config.eex

Generated `rel/config.exs` was giving a credo warning about the pipechain. Just added a minor fix for that :smile:

Pipechain should start with a raw value

---

docs/Phoenix Walkthrough.md
priv/templates/example_config.eex

Removed ambiguity in Phoenix walkthrough by explicitly focusing on Distillery with respect to Phoenix 1.3. Changed some language and grammar.
Only modified the markdown file.

Update Phoenix Walkthrough.md

---

lib/mix/lib/releases/config/config.ex
lib/mix/lib/releases/errors.ex

- Add documentation for `validate!/1`
- Fix type spec for `format_errors/1` function (there was a minor typo there)
- Fix syntax on `releases/errors.ex` related to spaces between tuple
elements

Improve docs and spec

---

docs/Phoenix Walkthrough.md

Phoenix 1.3 deprecated `phoenix.*` mix tasks in favor of `phx.*`.
Files modified/created in the walkthrough are now in different locations in a Phoenix 1.3 application.
Updates the deprecated `phoenix.*` mix tasks to `phx.*`.
Updates file paths to use the `assets` and `lib/phoenix_distillery_web` directories
that are created with a new Phoenix application.

Update deprecated Phoenix mix tasks and file paths for Phoenix 1.3

---

priv/templates/boot_win.eex

Replacement of all `exit` statements with `exit /b` in the boot_win.eex script that is used to create windows .bat files for a release. The current `exit` statements cause the calling shell to close, which is very annoying and prevents user from reading error messages outputed by the .bat file. Adding the /b flag will cause the batch script to stop but not the MS-DOS shell that called the script.

modify boot_win.eex to prevent exit statements to close the shell calling bat file

---

priv/libexec/config.sh

The -E switch is not a valid switch on smartos grep

Update extended-grep call to use egrep instead

---

priv/libexec/config.sh

Hi,
I'm trying to use a custom vm.args file using `VMARGS_PATH`, but I also want to use `REPLACE_OS_VARS=true` to replace variables inside my custom vm.args. I couldn't get it to work, I think, because `_configure_node` loads the node name from `VMARGS_PATH` instead of `DEST_VMARGS_PATH`. `DEST_VMARGS_PATH` has the replaced variables, but `VMARGS_PATH` is the original.
Let me know if I'm going about this the wrong way and I'll fix it. I haven't really tested this change thoroughly so it is really more of a proposal/question than an actual pull request. If you like the change, I'll test it properly.
The existing tests (`mix test`) pass, but I didn't see any tests for `config.sh` aside from integration tests. I could try and add an integration test that uses `VMARGS_PATH`?
Thanks!

Support REPLACE_OS_VARS on a custom vm.args.

---

lib/distillery/tasks/init.ex

- stop ignoring the .gitignore file in the /rel/plugins folder. this persists the plugins dir even if no code is added to it immediately.

don't ignore .gitignore

---

lib/mix/lib/releases/models/app.ex
lib/mix/lib/releases/utils.ex

We have a rather large project (145 apps/dependencies, all up) and distillery was taking an awfully long time to assemble each release (~10 minutes). Digging into what was taking the time, there's basically two calls that consume the vast bulk: `Mix.Dep.loaded([])` and `Mix.Dep.loaded([name], [])`, both in `app.ex` and both called for every application in the build. As far as I can tell, the first one always returns the same results and, at least in our case, takes several seconds each time. This patch moves the call up one level and reuses the result so that it's only made once per build rather than once per app. It roughly halved our release assembly time down to about 5 minutes.
If you can figure out a way to optimise the latter call, I will be forever in your debt :)
I also have a …

Only call Mix.Dep.loaded([]) once

---

docs/faq.md

Expand documentation regarding permissions, so that operators can choose between the needed set of permissions depending on the fact that they are using hot upgrades or not.
Refers to: https://github.com/bitwalker/distillery/issues/421#issuecomment-397834714

Add documentation details for needed permissions on hot upgrades

---

priv/libexec/commands/help.sh

The current version prints the full path for custom commands. This strips the path and removes the `.sh` suffix if there is one. This should make it easier to directly see the commands.

print the custom command without filepath

---

priv/libexec/erts.sh

Extended Mode uses { and } as special characters. Making grep implementations other then GNU grep fail.
From http://www.gnu.org/software/grep/manual/grep.html#Basic-vs-Extended ...
```
3.6 Basic vs Extended Regular Expressions
In basic regular expressions the meta-characters ‘?’, ‘+’, ‘{’, ‘|’, ‘(’, and ‘)’ lose their special meaning; instead use the backslashed versions ‘?’, ‘+’, ‘{’, ‘|’, ‘(’, and ‘)’.
Traditional egrep did not support the ‘{’ meta-character, and some egrep implementations support ‘{’ instead, so portable scripts should avoid ‘{’ in ‘grep -E’ patterns and should use ‘[{]’ to match a literal ‘{’.
GNU grep -E attempts to support traditional usage by assuming that ‘{’ is not special if it would be the start of an invalid interval specification. For example, the command …
```

Encapsulate { into [{] so it is not interpreted as 'grouping'

---

lib/distillery/tasks/init.ex

Fixes #446 
An issue when running mix release.init. I guess I needed to add compilers/0 for the mock to be proper.

Fixes #446

---

lib/mix/lib/releases/assembler.ex

Why?
Applications were being copied from the wrong location when `include_erts` is set to a path.

Use include_erts path when copying apps.

---

lib/mix/lib/releases/config/config.ex
priv/templates/release_rc_exec.eex

This PR does the following:
* Fixes issue with using `not` to check `include_erts` when it is a string path.
* Fixes issue were plugin modules are not called because the modules code is not loaded.

Fix issues with plugins

---

lib/mix/lib/releases/assembler.ex

Why?
If you set `include_erts` to an erts path in `before_assembly` the key for `erts_vsn` would represent the version on the host and not at the path

Move the call to Plugin.before_assembly to fix variable eval timing

---

lib/mix/lib/releases/config/providers/elixir.ex

Handle cases when `import_config("*.non_existent.exs")` doesn't return any config files.
```shell
==> Release failed: protocol Enumerable not implemented for nil
(elixir) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir) lib/enum.ex:141: Enumerable.reduce/3
(elixir) lib/enum.ex:2979: Enum.reject/2
(distillery) lib/mix/lib/releases/config/providers/elixir.ex:130: Mix.Releases.Config.Providers.Elixir.merge_imports/4
(distillery) lib/mix/lib/releases/config/providers/elixir.ex:98: Mix.Releases.Config.Providers.Elixir.do_read_quoted!/2
(distillery) lib/mix/lib/releases/config/providers/elixir.ex:31: Mix.Releases.Config.Providers.Elixir.read_quoted!/1
(distillery) lib/mix/lib/releases/assembler.ex:632: Mix.Releases.Assembler.do_generate_config_exs/1
(distillery) …
```

Handle case when wildcard doesn't resolve to any config files

---

lib/mix/lib/releases/config/providers/elixir.ex

I just tried the latest change and right now the conflict resolution is not recursive like how mix is by default and users might not expect this to be the case
This PR fixes that
```elixir
iex(1)> Mix.Config.merge([app: [url: "https://app.com"]], [app: [port: 443]])
[app: [url: "https://app.com", port: 443]]
iex(2)> Keyword.merge([app: [url: "https://app.com"]], [app: [port: 443]])
[app: [port: 443]]
```

Merge runtime config with compiled config

---

lib/mix/lib/releases/archiver.ex

fixes #464
I noticed that the filename does not match the template name required.

fix templatename to match filename

---

lib/mix/lib/releases/config/providers/elixir.ex

Stack trace:
```
=INFO REPORT==== 9-Aug-2018::18:45:26 ===
application: mix
exited: stopped
type: temporary
no function clause matching in Keyword.merge/3
(elixir) lib/keyword.ex:726: Keyword.merge("FOO", "FOO", #Function<6.105162710/3 in Mix.Config.merge/2>)
(elixir) lib/keyword.ex:739: Keyword.do_merge/6
(distillery) lib/mix/lib/releases/config/providers/elixir.ex:66: anonymous fn/1 in Mix.Releases.Config.Providers.Elixir.merge_config/1
(elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
(distillery) lib/mix/lib/releases/config/providers/elixir.ex:46: Mix.Releases.Config.Providers.Elixir.init/1
(distillery) lib/mix/lib/releases/config/provider.ex:97: anonymous fn/2 in Mix.Releases.Config.Provider.init/1
(elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
(distillery) …
```

Fix for merging configs

---

lib/distillery/tasks/release.ex

In 1.5.x `upfrom` option was merged with defaults https://github.com/bitwalker/distillery/blob/1.5.x/lib/distillery/tasks/release.ex#L217
and override `:latest` default. Probably its parsing was lost during 2.x upgrade.

Problem: upfrom option is not recognized

---

mix.exs

Changelog path has been changed from github.com to hexdocs.pm

fixed Changelog path to hexdocs.pm

---

docs/guides/phoenix_walkthrough.md

I don't think the Advanced deployment link still exists changing to a link that describes phoenix release setups
N/A

Update link to deployment docs

---

docs/guides/working_with_docker.md

The current working_with_docker.md file contains a mistake when setting production configuration variables. 
There seems to exist a different name convention between **config/docker.env** and **rel/config/config.exs**. This fixes the documentation to ensure that the tutorial works if followed properly.

Ensure docker.env file matches config.exs

---

docs/guides/systemd.md

👋
Is `ExecStop=/home/appuser/myapp/bin/myapp stop` really required for `Type=simple` service?

About stopping "simple" systemd service

---

docs/guides/deploying_to_aws.md

When I was skimming through the 'deploying to aws' guide it took me longer than expected to find the link to the distillery-aws-example repo after I saw it referenced in the 'Provisioning our pipeline' section. Thinking we could just make the reference a link to save other people a little bit of time?

Add link to distillery-aws-example repo reference

---

docs/guides/deploying_to_aws.md

I noticed an empty tip box. I think it's because of how it's indented, so here's the edit accordingly. Just a guess though, never used mkdocs before 😊

Fix empty tip box in 'deploying to aws' guide

---

lib/distillery/tasks/release.ex

Currently --profile switch doesn't work, after adding some debug log and inspecting, I figured out it's because the --profile args aren't converted to atoms so `Map.get` can't find the specified environment (and release name).
with `--profile`:
```
selected_environment: "prod",
selected_release: "xyz",
```
with `--env`:
```
selected_environment: :prod,
selected_release: :default,
```

Convert --profile args to atoms

---

docs/config/pidfiles.md
docs/guides/running_migrations.md
docs/upgrading_to_2_0.md

- Quoting of pidfile path need to use both quotes.
- Deleting the code to check the application in the Migration example, as they are loaded already

Spurious code in migration; path quoting pidfile

---

mix.exs

It seems `Logger` is not used at all, and my release works fine without it as well. I also [posted a question on Elixir Forum](https://elixirforum.com/t/why-is-logger-included-in-extra-applications-by-default/16306) and would love some feedback on this.

Remove logger

---

.formatter.exs

Feels like `set include_erts: true` should be formatted as is.

Add set/1 to formatter ignore

---

Dockerfile.alpine

Alpine container does not have pushd, popd and bash.
I removed them.
WORKDIR is set to `/opt` so I think we don't need pushd/popd.

FIX Dockerfile.alpine for docker build

---

docs/guides/building_in_docker.md

TL;DR docs example wasn't in the right directory
I wanted to use the grep script (below) in your docs because well it looked great!
When I ran it, it was getting me the output:
```shell
grep: mix.exs: No such file or directory
grep: mix.exs: No such file or directory
```
The script in your docs that I'm referring to:
```shell
APP_NAME="$(grep 'app:' mix.exs | sed -e 's/\[//g' -e 's/ //g' -e 's/app://' -e 's/[:,]//g')"
APP_VSN="$(grep 'version:' mix.exs | cut -d '"' -f2)"
```
(the "Contribution"). My Contribution is …

APP_NAME and APP_VSN calculation needs to run in the right directory

---

priv/templates/release_rc_win_exec.eex

According to [documentation](https://ss64.com/nt/if.html), equality comparison in Windows batch files should use the [`equ` operator](https://ss64.com/nt/equ.html).
The previous version would output `eq was unexpected at this time.`.
This PR addresses issue #540 .

Fix the equality comparison in windows batch files

---

docs/extensibility/boot_hooks.md

I stumbled a bit on this small thing in the guide as I initially thought `rel/hooks/pre_start` was the script itself, not a directory. The error messages made it fairly clear to correct, but not before I wondered if I did something else wrong.

Clarify the hooks are directories

---

lib/mix/lib/releases/runtime/pidfile.ex

The why:
warning: variable "err" is unused
lib/mix/lib/releases/runtime/pidfile.ex:50
not a big deal, right?
- [- ] New functions have typespecs, changed functions were updated
- [- ] Same for documentation, including moduledocs
- [ -] Tests were added or updated to cover changes
- [- ] Commits were squashed into a single coherent commit
NOTE: If you submit a PR …

build warning

---

docs/guides/systemd.md

I didn't find any directory named "logs" under my release root. All I can find is `'var/log'`. Feel free to close it if I'm wrong.

Fix log location

---

docs/guides/working_with_docker.md

A Makefile needs tab character instead of space character  for indentation.
Before this changes, when we ran `make`, it would bring an error message following:
`Makefile:18: *** multiple target patterns.  Stop.`

Fix Makefile syntax in "Deploying with Docker"

---

docs/guides/running_migrations.md

I've encountered the problem solved by this commit while I was learning Distillery through this tutorial - I think that it'd be nice to have the place for `App.ReleaseTasks` mentioned in the docs, especially for beginners.
considered, it must contain your agreement …

Docs: Add a tip about where to put the migration runner module

---

lib/mix/lib/releases/overlays.ex

Hi, thanks for the package!
I found that debug output formatting is a bit broken
and also color extends to the following output.
I just added reset function at the and of the lines

fix io color formatting

---

mkdocs.yml

https://python-markdown.github.io/change_log/release-2.5/#backwards-incompatible-changes
> The previously documented method of appending the extension configuration as a string to the extension name will be deprecated in Python-Markdown version 2.6
When I installed and executed mkdocs for cheking improved documents, mkdocs didn't work following like:
```
$ mkdocs build
ERROR   -  Config value: 'markdown_extensions'. Error: Failed loading extension
"markdown.extensions.toc(permalink=true)".
Aborted with 1 Configuration Errors!
```
The versions were:
- mkdocs: 1.0.4
- markdown: 3.0.1
```
$ pip3 show mkdocs
Name: mkdocs
Version: 1.0.4
Summary: Project documentation with Markdown.
Home-page: https://www.mkdocs.org
Author: Tom Christie
Author-email: tom@tomchristie.com
License: BSD
Location: …
```

Fix the setting for generating docs with the latest Python-Markdown

---

docs/guides/phoenix_walkthrough.md

I've updated the broken (404) links to appup and relup in the Phoenix walkthrough docs.

Update links to appup and relup in the docs

---

.gitignore
lib/mix/lib/releases/assembler.ex
priv/templates/release_rc_win_main.ps1.eex

This in an attempt to fix issue #572 .
After a lot of trials and errors I figured out that the problem happened because of the presence of the `erl.ini` file inside the included erts folder. The `erl.ini` file contained some paths that were referring the erlang binaries of the building machine and (obviously) they didn't exist on the machine where the release was running.
I tried to manually remove the `erl.ini` file and everything seemed fine. So, I added a step to remove the `erl.ini` file when creating a release including erts.
Unfortunately I wasn't able to find a reference where was explained if the `erl.ini` file is somewhat mandatory or not (by my tests it seems not...)
I certify that I …

572 fix windows releases

---

docs/changelog.md
docs/config/pidfiles.md
docs/upgrading_to_2_0.md
lib/mix/lib/releases/runtime/pidfile.ex

Connected with issue https://github.com/bitwalker/distillery/issues/582
**Current behaviour:**
When PID file configuration is loaded from the vm.args file in any of the following formats:
```
-kernel pidfile "'etc/server.pid'"
-kernel pidfile '"etc/server.pid"'
```
it creates the following error
```
{"could not start kernel pid",'Elixir.Mix.Releases.Runtime.Pidfile',{error {invalid_pidfile_config,'etc/server.pid'}}}
could not start kernel pid (Elixir.Mix.Releases.Runtime.Pidfile) ({error {invalid_pidfile_config,etc/server.pid}})
```
This prevents from having a working pidfile config in vm.args file
**Solution:**
After some debugging I found that in case of the second format (`'"etc/server.pid"'`) the path variable is a list, while in the code there is only check for binary …

fix loading pidfile config from vm args

---

docs/guides/running_migrations.md

The whole code block is missing now from the doc https://hexdocs.pm/distillery/guides/running_migrations.html:
Append a blank line fix the problem in my test:

Fix formatting.

---

lib/mix/lib/releases/archiver.ex
lib/mix/lib/releases/assembler.ex

The rel directory should mimic what the actual output of the release. The setting `set strip_debug_info: true` makes modifications to the tar and not the release directory. This produces unexpected results for scenarios where the archive step is skipped. This PR moves this step to the assembly phase.

Strip release in assembler instead of archiver.

---

priv/libexec/commands/win/install.ps1

We have had extremely large log files generated on deploys to Windows servers. It seems like it is caused by the `-debugType new` option.
From the [erlsrv](http://erlang.org/doc/man/erlsrv.html) documentation:
>The new and reuse options might seem convenient in a production system, but consider that the logs grow indefinitely during the system lifetime and cannot be truncated, except if the service is restarted.
>In short, the DebugType is intended for debugging only. Logs during production are better produced with the standard Erlang logging facilities.
This pull request removes the `-debugType` flag entirely which has solved the problem for us. I am not sure what to do about the test section of the checklist, let me know if there is anything you require me to do here.
**By submitting …

Windows: Remove erlsrv `-debugType new` option from install to stop unbounded logs

---

docs/guides/phoenix_walkthrough.md

Updates the Phoenix Walkthrough Guide to match what is included in a fresh Phoenix 1.4.3 app. Using `webpack` instead of `brunch`. Also ` config/prod.exs` now has a slightly different `http` config. Addresses https://github.com/bitwalker/distillery/issues/648
By submitting this PR, you agree to the following statement, please read before submission!
I'll review the …

Updates Guides/Phoenix to match 1.4.3 phoenix app

---

docs/guides/deploying_to_aws.md

As described here: https://github.com/bitwalker/distillery-aws-example/issues/5#issue-381257706, S3 bucket names must be globally unique. In the CF template for the pipeline (https://github.com/bitwalker/distillery-aws-example/blob/master/templates/pipeline.yml#L72), the bucket name is created like `"${ApplicationName}-builds"`. Unless users of this template set `APP_NAME` then the default app name `distillery-aws-example` will be used to generate the bucket name, so bucket name will be `distillery-aws-example-builds`. A bucket with this name already exists so the bucket creation will fail. Here I propose to suggest users set a unique app name to avoid this, seems like the simplest way to avoid confusion. Alternatively I can create a PR allowing users to specify the bucket name as an …

Suggest setting unique app name to avoid S3 conflicts

---

lib/mix/lib/releases/models/release.ex

Fixing a misspelling in the docs for `Release.get_code_paths/1`.

Fix typo in Release.get_code_paths/1

---

lib/mix/lib/releases/runtime/control.ex

The describe command should print the release version to give more info about it.

Add release version to describe command

---

lib/distillery/lib/cookies.ex
test/cases/cookies_test.exs

Prevents Distillery from generating cookies that contain commas. In our experience with a cookie that contained a comma, our nodes had issues connecting. When we replaced the comma with another character, the nodes were able to connect properly.

Prevents generating cookies that contain commas

---

test/cases/integration_test.exs

Fixes
```
$ mix test
.....................warning: variable "err" does not exist and is being expanded to "err()", please use parentheses to remove the ambiguity or change the variable name
test/cases/integration_test.exs:263
...............................................................................
OK, passed 100 tests
.
== Compilation error in file test/cases/integration_test.exs ==
** (CompileError) test/cases/integration_test.exs:263: undefined function err/0
(elixir) src/elixir_locals.erl:107: :elixir_locals."-ensure_no_undefined_local/3-lc$^0/1-0-"/2
(elixir) src/elixir_locals.erl:107: anonymous fn/3 in :elixir_locals.ensure_no_undefined_local/3
(stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
(elixir) lib/code.ex:767: Code.require_file/2
(elixir) …
```

Fix compilation error

---

lib/distillery/tasks/init.ex

When I run `mix distillery.init`, I get the following at the bottom of `rel/config.exs`. Notice the release names are missing.
```
release : do
set version: current_version(:)
set applications: [
:runtime_tools
]
end
```
I think this is because of [this recently changed line](https://github.com/bitwalker/distillery/commit/c802067f8cf201172197192889b7d1f41f26df8d#diff-8b07b1cd7c8f470e4c155c0a09345be6R169).
And related to [this default value](https://github.com/bitwalker/distillery/commit/c802067f8cf201172197192889b7d1f41f26df8d#diff-8b07b1cd7c8f470e4c155c0a09345be6R116).
This ran fine when I tested it manually, but I had some trouble getting the integration tests to run on master or even the 2.0.14 tag so I'm not sure if this breaks anything else. I actually wanted to delete the nil …

Fixes generated rel/config.exs when release name is not provided.

---

docs/extensibility/shell_scripts.md

The `<vsn>` string was not seen as it was attempted to interpret it as a
tag. Also the variable does not hold the trailing slash.

Fix REL_DIR in documentation

---

priv/templates/release_rc_exec.eex

Fixes issue with trying to boot initial release. 
```
_build/dev/rel/example/bin/example console
cp: /Users/jschneck/Developer/nerves/shoehorn/example/_build/dev/rel/example/var/start_erl.data: No such file or directory
```

Ensure RELEASE_MUTABLE_DIR exists before writing to it

---

priv/templates/release_rc_win_exec.eex

I was running into an issue where a batch file produced from this template was not working if I put it in a directory structure which contained spaces. I noticed that the boot script was being quoted with unescaped double quotes, within a string enclosed in double quotes, and that looked wrong. I was able to run the batch file in directory structures with and without spaces if I instead quoted the boot script with single quotes or escaped double quotes `\"`. I don't fully understand all the nuances with escaped quotes in batch files and powershell, but using single quotes is similar to how it was suggested that powershell be called from a batch file [here](https://stackoverflow.com/a/20059213), so I went with that.
I'm not familiar with this project, so I'm not sure how to add tests for …

Properly quote the boot_script in the windows batch file template

---

priv/libexec/commands/foreground.sh

foreground.sh: Double detach the post_start subshell to ensure it is
reaped properly by 'init' after it has completed and avoid a zombie
process hanging around.
In Docker/systemd configs the current foreground script leaves an annoying zombie process hanging around. This change gets rid of that.
```
$ docker exec b4c3d7fce641 ps -ef
PID   USER     TIME  COMMAND
1 root      0:00 /dev/init -- /bin/sh -c exec /opt/app/bin/${APP_NAME} foreground
6 root      0:05 {beam.smp} /opt/app/releases/0.1.0/ant_farm.sh -Bd -- -root /opt/app -progname opt/app/releases/0.1.0/ant_farm.sh -- -home /root -- -boot_var ERTS_LIB_DIR /opt/app/lib -config /opt/app/var/sys.config -pa /opt/app/lib/ant_farm-0.1.0/consolidated -noshell -noshell -noinput -boot /opt/app/releases/0.1.0/ant_farm -name ant_farm@127.0.0.1 …
```

Stop post start subshell ending up as a zombie

---

priv/libexec/erts.sh

It's on path in all other conditional branches, so there's no reason
it's not set in the case of bundled erts and the default boot file.

Add "consolidated" to path in `erl` helper

---

docs/introduction/installation.md
lib/distillery/tasks/clean.ex
lib/distillery/tasks/gen.appup.ex
lib/distillery/tasks/release.ex

There were few leftovers in the documentation still referring to `release.init`.

Update references to distillery.init

---

lib/distillery/releases/assembler.ex

The option `include_src: true` now includes the source code of
applications which are built from this project. That means:
- the top-level app
- umbrella apps
- dependencies
Fix #683

Include source of applications from current project

---

priv/templates/release_rc_exec.eex

This is a simple change to fix the issue in #693 - where the start_erl.data file in releases/ does not get copied into the mutable dir when the directory already exists. 
It is a slightly better fix than #703 since it checks if the start_erl.data file in releases dir is newer than the var version first, instead of blindly copying it every single time. 
- [ n/a] New functions have typespecs, changed functions were updated
- [ n/a] Same for documentation, including moduledocs
- [?] Tests were added or updated to cover changes - **not sure how to test this change, please advise**
related material intended to be …

fix for start_erl.data - old release getting started after deployment

---

docs/guides/systemd.md

Useful note, as it's not obvious that you need to enable the service if you want it to be restarted when the server is restarted.

Note about enabling service to start on boot

---

docs/guides/systemd.md

I've run into issues where Systemd was unable to detect that my app had crashed because the app failed to remove its pidfile. This happened to me because the Beam was killed using a `SIGKILL` by Ubuntu's "Out Of Memory Killer". Under these conditions, the app is killed suddenly and wasn't able to remove it's pidfile. I am using the [pid_file 0.1.0](https://github.com/OvermindDL1/pid_file) to manage pidfiles.

Note inability to remove pifile on SIGKILL
